#!/bin/bash

bspc monitor -d 1 2 3 4

bspc config border_width 2
bspc config window_gap 10
bspc config focused_border_color '#FFFFFF'
bspc config initial_polarity second_child
bspc config gapless_monocle on
bspc config borderless_monocle on
bspc config auto_cancel on
bspc config click_to_focus on
